- assert:
    that: "{{ item }} is defined and {{ item }} | length > 0"
    fail_msg: "Undefined or empty variable '{{ item }}'"
  with_items:
    - k8s_base_node_type
    - k8s_base_control_plane_endpoint

- name: Check node type
  assert:
    that:
      - k8s_base_node_type in [ "master", "worker" ]
    fail_msg: "Incorrect node type ('k8s_base_node_type'): got '{{ k8s_base_node_type }}', expected either 'master' or 'worker'"
