# - block:
#     - name: Check Helm installation status
#       stat:
#         path: "{{ k8s_base_helm_bin }}"
#       register: _helm_bin
#     # ---
#     - name: Set Helm installation status
#       set_fact:
#         k8s_base_helm_exists: "{{ _helm_bin.stat.exists | bool }}"


- block:
    # ---
    - name: Check node service status
      service_facts:
    # ---
    - name: Set node service status
      set_fact:
        k8s_base_kubelet_running: "{{ ansible_facts.services['kubelet.service'].state | default ('unknown') == 'running' }}"


- block:
    # ---
    - name: Check kubelet health
      uri:
        url: "{{ k8s_base_health_url }}"
        return_content: yes
        timeout: 2
      failed_when: false
      register: _healtz_text
    # ---
    - name: Set kubelet health
      set_fact:
        k8s_base_kubelet_healthy: "{{ _healtz_text.content | default('-') == 'ok' }}"
    # ---


- name: Check if any node is unconfigured or unhealthy
  set_fact:
    play_has_unconfigured_nodes: yes
  delegate_to: localhost
  run_once: yes
  when:
    - not hostvars[item].k8s_base_kubelet_healthy
  with_items: "{{ ansible_play_hosts }}"


- block:
    # ---
    - name: Check cluster status
      shell: >
        kubectl cluster-info
      environment:
        KUBECONFIG: "{{ k8s_base_kubeconfig }}"
      register: _kubectl_cs_code
      failed_when: false
      changed_when: false
      when:
        - k8s_base_node_type == "master"
    # ---
    - name: Set cluster status
      set_fact:
        k8s_base_cluster_running: "{{ _kubectl_cs_code.rc | default('1') == 0 }}"


# - name: Set stats (play level)
#   set_stats:
#     per_host: no
#     data:
#       play_has_unconfigured_nodes: "{{ play_has_unconfigured_nodes | default(false) }}"
#   delegate_to: localhost
#   run_once: yes


- name: Set stats
  set_stats:
    per_host: yes
    aggregate: yes
    data:
      k8s_base_helm_exists: "{{ k8s_base_helm_exists | default(false) }}"
      k8s_base_kubelet_running: "{{ k8s_base_kubelet_running | default(false) }}"
      k8s_base_kubelet_healthy: "{{ k8s_base_kubelet_healthy | default(false) }}"
      k8s_base_cluster_running: "{{ k8s_base_cluster_running | default(false) }}"
  # delegate_to: localhost
  # run_once: yes
