# Kubernetes
#
# Install and start Kubernetes on every hosts.

- include_tasks:
    file: "install_{{ ansible_distribution|lower }}.yml"

- name: Install Kubernetes
  package:
    name: "{{ k8s_base_packages }}"
    state: present

- name: Start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes


# Python
#
# Install PIP and Ansible dependencies to interact with Kubernetes on master nodes.
- block:
    # ---
    - name: Install Python PIP
      package:
        name:
          - python3-pip
        state: present
    # ---
    - name: Install Kubernetes Python dependencies for Ansible
      pip:
        name:
          - PyYAML
          - openshift
          - grpcio
          - docker
        state: present
  when:
    - k8s_base_node_type == "master"


# Helm
#
# Installs Helm if its not already installed.
# If the tags include 'force_helm', Helm is reinstalled.
# - block:
#     # ---
#     - name: Create Helm temporary installation directory
#       tempfile:
#         state: directory
#       register: helm_unpack_dir
#     # ---
#     - name: Unpack Helm
#       unarchive:
#         src: "files/{{ k8s_base_helm_package_src }}"
#         dest: "{{ helm_unpack_dir.path }}/"
#     # ---
#     - name: Install Helm
#       copy:
#         remote_src: yes
#         src: "{{ helm_unpack_dir.path }}/{{ k8s_base_helm_package_dis }}/helm"
#         dest: "{{ k8s_base_helm_install_dir }}/"
#     # ---
#     - name: Setup Helm permissions
#       file:
#         path: "{{ k8s_base_helm_bin }}"
#         mode: "o+x"
#     # ---
#     - name: Remove Helm temporary installation directory
#       file:
#         path: "{{ helm_unpack_dir.path }}"
#         state: absent
#     # ---
#   when:
#     - k8s_base_node_type == "master"
#     - not k8s_base_helm_exists or 'force_helm' in ansible_run_tags
