# Reset cluster
#
# This task is placed at top in order to bypass all assertions and avoid
# information gathering.
- name: Reset Kubernetes
  include_tasks:
    file: teardown.yml
    apply: { tags: [ teardown ] }
  tags:
    - teardown


# Remove Kubernetes
#
# This task is placed at top in order to bypass all assertions and avoid
# information gathering.
- name: Remove Kubernetes
  include_tasks:
    file: remove.yml
    apply: { tags: [ remove ] }
  tags:
    - remove


# Assertions
#
# Assert the the role has been invoked with the correct tags and with a valid set of hosts.
# This apply only for installation and cluster management.
- name: Assertions
  include_tasks:
    file: assert.yml
    apply: { tags: [ setup ] }
  tags:
    - setup


# Facts collection
#
# Collect custom facts 
- name: Preflight facts collection
  include_tasks:
    file: facts.yml
    apply: { tags: [ setup ] }
  tags:
    - setup


# Installation
#
# Install Kubernetes, its requirements, Helm and Ansible's Python packages needed
# to operate the cluster.
- name: Installation
  include_tasks:
    file: install.yml
    apply: { tags: [ setup ] }
  tags:
    - setup


# Prepare kubeconfig
#
# Ensure that the latest version of the system's default kubeconfig is installed
# and that the next tasks will run seamlessly.
- block:
    # ---
    - name: Create kubeconfig root directory
      file:
        path: "{{ k8s_base_kubeconfig | dirname }}"
        state: directory
    # ---
    - name: Copy kubeconfig
      copy:
        remote_src: yes
        src: "{{ k8s_base_kubeconfig_default }}"
        dest: "{{ k8s_base_kubeconfig }}"
      failed_when: false
    # ---
  when:
    - k8s_base_node_type == "master"
  tags:
    - setup


# Deploy cluster
#
# Deploy the Kubernetes cluster (master and worker nodes)
- name: Cluster setup
  include_tasks:
    file: cluster.yml
    apply: { tags: [ setup ] }
  tags:
    - setup


# Facts collection
#
# Collect custom facts
- name: Postflight facts collection
  include_tasks:
    file: facts.yml
    apply: { tags: [ always, stats ] }
  tags:
    - always
    - stats
